// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://edaifwqfglwsoozuxjca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImVkYWlmd3FmZ2x3c29venV4amNhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY1NTQxMzcsImV4cCI6MjA3MjEzMDEzN30.KncLiKJbu53ydBk-myHCzZLEcQKZKcwaEzAMbsPxZQQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});